//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LF10Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LF10Demo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LF10Demo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LF10Demo.Properties.LF10Demo", typeof(LF10Demo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abort.
        /// </summary>
        internal static string CTRL_TXT_Abort {
            get {
                return ResourceManager.GetString("CTRL_TXT_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &amp;Info.
        /// </summary>
        internal static string CTRL_TXT_AssInfo {
            get {
                return ResourceManager.GetString("CTRL_TXT_AssInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Back.
        /// </summary>
        internal static string CTRL_TXT_Back {
            get {
                return ResourceManager.GetString("CTRL_TXT_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear &amp;History.
        /// </summary>
        internal static string CTRL_TXT_ClearHistory {
            get {
                return ResourceManager.GetString("CTRL_TXT_ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear &amp;Tenprints.
        /// </summary>
        internal static string CTRL_TXT_ClearTenprints {
            get {
                return ResourceManager.GetString("CTRL_TXT_ClearTenprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string CTRL_TXT_Edit {
            get {
                return ResourceManager.GetString("CTRL_TXT_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string CTRL_TXT_Exit {
            get {
                return ResourceManager.GetString("CTRL_TXT_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string CTRL_TXT_File {
            get {
                return ResourceManager.GetString("CTRL_TXT_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string CTRL_TXT_Help {
            get {
                return ResourceManager.GetString("CTRL_TXT_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next.
        /// </summary>
        internal static string CTRL_TXT_Next {
            get {
                return ResourceManager.GetString("CTRL_TXT_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string CTRL_TXT_Options {
            get {
                return ResourceManager.GetString("CTRL_TXT_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string CTRL_TXT_Prev {
            get {
                return ResourceManager.GetString("CTRL_TXT_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Start.
        /// </summary>
        internal static string CTRL_TXT_Start {
            get {
                return ResourceManager.GetString("CTRL_TXT_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string CTRL_TXT_Tools {
            get {
                return ResourceManager.GetString("CTRL_TXT_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string TXT_Auto {
            get {
                return ResourceManager.GetString("TXT_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detection.
        /// </summary>
        internal static string TXT_AutoDetection {
            get {
                return ResourceManager.GetString("TXT_AutoDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing Failed.
        /// </summary>
        internal static string TXT_CapturingFailed {
            get {
                return ResourceManager.GetString("TXT_CapturingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing Sequence.
        /// </summary>
        internal static string TXT_CaputuringSequence {
            get {
                return ResourceManager.GetString("TXT_CaputuringSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Scanner Contamination!.
        /// </summary>
        internal static string TXT_CheckScannerContamination {
            get {
                return ResourceManager.GetString("TXT_CheckScannerContamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Sequence.
        /// </summary>
        internal static string TXT_CompleteSequence {
            get {
                return ResourceManager.GetString("TXT_CompleteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contamination.
        /// </summary>
        internal static string TXT_Contamination {
            get {
                return ResourceManager.GetString("TXT_Contamination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Capturing.
        /// </summary>
        internal static string TXT_CurrentCapturing {
            get {
                return ResourceManager.GetString("TXT_CurrentCapturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string TXT_Duration {
            get {
                return ResourceManager.GetString("TXT_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TXT_Error {
            get {
                return ResourceManager.GetString("TXT_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TXT_Exit {
            get {
                return ResourceManager.GetString("TXT_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Detection.
        /// </summary>
        internal static string TXT_FingerDetection {
            get {
                return ResourceManager.GetString("TXT_FingerDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger Print.
        /// </summary>
        internal static string TXT_FingerPrint {
            get {
                return ResourceManager.GetString("TXT_FingerPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger Prints.
        /// </summary>
        internal static string TXT_FingerPrints {
            get {
                return ResourceManager.GetString("TXT_FingerPrints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FourprintSegmenation intialization.
        /// </summary>
        internal static string TXT_FourprintSegmenationInit {
            get {
                return ResourceManager.GetString("TXT_FourprintSegmenationInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left and Right Thumb.
        /// </summary>
        internal static string TXT_LeftAndRightThumb {
            get {
                return ResourceManager.GetString("TXT_LeftAndRightThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Four Fingers.
        /// </summary>
        internal static string TXT_LeftFourFingers {
            get {
                return ResourceManager.GetString("TXT_LeftFourFingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Index.
        /// </summary>
        internal static string TXT_LeftIndex {
            get {
                return ResourceManager.GetString("TXT_LeftIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Little.
        /// </summary>
        internal static string TXT_LeftLittle {
            get {
                return ResourceManager.GetString("TXT_LeftLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Middle.
        /// </summary>
        internal static string TXT_LeftMiddle {
            get {
                return ResourceManager.GetString("TXT_LeftMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ring.
        /// </summary>
        internal static string TXT_LeftRing {
            get {
                return ResourceManager.GetString("TXT_LeftRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Thumb.
        /// </summary>
        internal static string TXT_LeftThumb {
            get {
                return ResourceManager.GetString("TXT_LeftThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF10 intialization.
        /// </summary>
        internal static string TXT_LF10Init {
            get {
                return ResourceManager.GetString("TXT_LF10Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LF10 intialization.
        /// </summary>
        internal static string TXT_LF10Intialization {
            get {
                return ResourceManager.GetString("TXT_LF10Intialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifeness Detection Time.
        /// </summary>
        internal static string TXT_LifenessDetectionTime {
            get {
                return ResourceManager.GetString("TXT_LifenessDetectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifeness Score .
        /// </summary>
        internal static string TXT_LifenessScore {
            get {
                return ResourceManager.GetString("TXT_LifenessScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string TXT_Manual {
            get {
                return ResourceManager.GetString("TXT_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIST Qaulity Check intialization.
        /// </summary>
        internal static string TXT_NISTQaulityCheckInit {
            get {
                return ResourceManager.GetString("TXT_NISTQaulityCheckInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIST Quality.
        /// </summary>
        internal static string TXT_NISTQualityTime {
            get {
                return ResourceManager.GetString("TXT_NISTQualityTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Rolled.
        /// </summary>
        internal static string TXT_OneRolled {
            get {
                return ResourceManager.GetString("TXT_OneRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible Fake score.
        /// </summary>
        internal static string TXT_PossibleFakeScore {
            get {
                return ResourceManager.GetString("TXT_PossibleFakeScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string TXT_Process {
            get {
                return ResourceManager.GetString("TXT_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string TXT_Quality {
            get {
                return ResourceManager.GetString("TXT_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality to bad.
        /// </summary>
        internal static string TXT_QualityToBad {
            get {
                return ResourceManager.GetString("TXT_QualityToBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Four Fingers.
        /// </summary>
        internal static string TXT_RightFourFingers {
            get {
                return ResourceManager.GetString("TXT_RightFourFingers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Index.
        /// </summary>
        internal static string TXT_RightIndex {
            get {
                return ResourceManager.GetString("TXT_RightIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Little.
        /// </summary>
        internal static string TXT_RightLittle {
            get {
                return ResourceManager.GetString("TXT_RightLittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Middle.
        /// </summary>
        internal static string TXT_RightMiddle {
            get {
                return ResourceManager.GetString("TXT_RightMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Ring.
        /// </summary>
        internal static string TXT_RightRing {
            get {
                return ResourceManager.GetString("TXT_RightRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Thumb.
        /// </summary>
        internal static string TXT_RightThumb {
            get {
                return ResourceManager.GetString("TXT_RightThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled Area.
        /// </summary>
        internal static string TXT_RolledArea {
            get {
                return ResourceManager.GetString("TXT_RolledArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentation.
        /// </summary>
        internal static string TXT_Segmentation {
            get {
                return ResourceManager.GetString("TXT_Segmentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentation &amp; NFIQ.
        /// </summary>
        internal static string TXT_SegmentationAndNFIQ {
            get {
                return ResourceManager.GetString("TXT_SegmentationAndNFIQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Complete!.
        /// </summary>
        internal static string TXT_SequenceComplete {
            get {
                return ResourceManager.GetString("TXT_SequenceComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Count.
        /// </summary>
        internal static string TXT_SequenceCount {
            get {
                return ResourceManager.GetString("TXT_SequenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Mode.
        /// </summary>
        internal static string TXT_SequenceMode {
            get {
                return ResourceManager.GetString("TXT_SequenceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Nr:.
        /// </summary>
        internal static string TXT_SequenceNr {
            get {
                return ResourceManager.GetString("TXT_SequenceNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string TXT_Start {
            get {
                return ResourceManager.GetString("TXT_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string TXT_Stop {
            get {
                return ResourceManager.GetString("TXT_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string TXT_Warning {
            get {
                return ResourceManager.GetString("TXT_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSQ Compression.
        /// </summary>
        internal static string TXT_WSQCompression {
            get {
                return ResourceManager.GetString("TXT_WSQCompression", resourceCulture);
            }
        }
    }
}
